### ISSUE TITLE
Breaks source maps

### ISSUE THREAD

**Issue by infernalmaster** [trentearl/gulp-css-url-adjuster#5]
It uses https://github.com/reworkcss/rework and because of that css code is reformated and line numbers is changed. So source maps doesn't work.  This should be mentioned in documentation or maybe implement that functionality without [rework](https://github.com/reworkcss/rework)

**Comment by faragly** [comment]
How did you decide this? You can explain the code? I will be very grateful

**Comment by Guicom** [comment]
I figure the same issue. As we use SASS, we can create some mixin or function for doing this job until this plugin can support sourcemap.

So we can create this mixin and function : 

```
$image-path : '../../my_path/images';

@mixin bg-image($image, $repeat, $x, $y, $color:transparent) {
  background: url(unquote($image-path)/unquote($image)) $repeat $x $y $color;
}

@function image($image) {
  @return url(unquote($image-path)/unquote($image));
}
```

And we can use them like this : 

```
.jumbotron {
  @include bg-image('logo.png', no-repeat, bottom, left);
  background: image('logo.png') no-repeat bottom left;
}
```

**Comment by ijabit** [comment]
This issue has been out there for a while. I'm also seeing broken sourcemaps when this plugin is used. Is there any fix? @Guicom has a fix, but only if you control the SASS code, which I don't if the code is from a vendor (KendoUI).
